# Generated by Django 5.0.7 on 2024-07-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
